#!/bin/bash
if [ -z "$1" ]
  then
    echo "Parent branch to do diff not specified. Defaulting to master"
    FILES_TO_FIX=$(git diff --name-only origin/master)
  else
    FILES_TO_FIX=$(git diff --name-only $BRANCH)
fi

echo "Files to fix:" $FILES_TO_FIX;

for i in $FILES_TO_FIX
do
  php-cs-fixer fix $i
done
