name: PHP Composer

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 7.4]
        stability: [prefer-stable]
    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

    - name: Code style and psalm
      run: composer run-script ci
    - name: "Check for BC breaks"
      run: "vendor/bin/roave-backward-compatibility-check"
